name: Checkmarx One Scan

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  cx-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 #v3.0.0
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@latest # main
        with:
          base_uri: ${{ secrets.BASE_URI_CANARY }}
          cx_tenant: ${{ secrets.TENANT_CANARY }}
          cx_client_id: ${{ secrets.CLIENT_ID_CANARY }}
          cx_client_secret: ${{ secrets.AST_CLIENT_SECRET_CANARY }}
          additional_params: --scan-types container-security --debug
